[project]
name = "stock-tech"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "akshare>=1.16.95",
    "flask>=3.1.1",
    "matplotlib>=3.10.3",
    "pandas>=2.2.3",
]
