name: Deploy to CentOS 7 Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync Code to Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SSH_USER: ${{ secrets.SSH_USERNAME }}
        PROJECT_DIR: "/var/www/myflaskapp"
      run: |
        # 同步代码到服务器（排除不需要的文件）
        rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          --exclude '.git/' \
          --exclude 'venv/' \
          --exclude '__pycache__/' \
          --exclude '.env' \
          ./ $SSH_USER@$SERVER_IP:$PROJECT_DIR

        # 触发服务器端部署
        ssh $SSH_USER@$SERVER_IP "cd $PROJECT_DIR && uv sync && source .venv/bin/activate && systemctl restart stock-teach"